# Generated by Django 2.2.3 on 2019-07-20 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KaboFixApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaborequest',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KaboProblem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='kaborequest',
            name='likes',
        ),
        migrations.AddField(
            model_name='kaborequest',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kaborequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
